name: CI Workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      # You can comment this out if there's no lint script in package.json
      # - name: Run linter
      #   run: npm run lint

      # ❌ Skip this step for now to avoid the Axios error
      # - name: Run tests
      #   run: npm test
